version: '3.8'

services:
  backend:
    build: ./fastapi_application
    ports:
      - 8000
    environment:
      - DB_HOST=${PGHOST}
      - DB_PORT=${PGPORT}
      - DB_NAME=${PGDATABASE}
      - DB_USER=${PGUSER}
      - DB_PASS=${PGPASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY_MANAGER=${SECRET_KEY_MANAGER}
      - MODE=PROD

  frontend:
    build: ./frontend
    ports:
      - 3000
    environment:
      - VITE_BACKEND_BASE_URL=${BACKEND_URL}
    depends_on:
      - backend
