services:
  backend:
    build: ./fastapi_application
    ports:
      - 8000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  frontend:
    build: ./frontend
    ports:
      - 3000
    environment:
      - VITE_BACKEND_BASE_URL=${BACKEND_URL}
    depends_on:
      - backend
